// <auto-generated />
using System;
using ENOC.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ENOC.Migrations
{
    [DbContext(typeof(ENOCContext))]
    [Migration("20221111165048_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ENOC.data.Facilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("facilities");
                });

            modelBuilder.Entity("ENOC.data.SiteFacilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FacilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FacilitiesId");

                    b.ToTable("siteFacilities");
                });

            modelBuilder.Entity("ENOC.data.SiteFacilities", b =>
                {
                    b.HasOne("ENOC.data.Facilities", "Facilities")
                        .WithMany("SiteFacilities")
                        .HasForeignKey("FacilitiesId");

                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("ENOC.data.Facilities", b =>
                {
                    b.Navigation("SiteFacilities");
                });
#pragma warning restore 612, 618
        }
    }
}
